### ISSUE TITLE
Good start!

### ISSUE THREAD

**Issue by phylischumba** [Albertino2020/the-next-web-clone#2]
Hello @rajkumardas2701 & @Albertino2020 
Your next web clone is good, you have had a good start. The navbar looks okay as well as the first section.
One observation we have made, check on your HTML semantics and the web responsiveness as you keep working on the project.

We wish you well!

**Comment by rajkumardas2701** [comment]
Thank you for the feedback. We have implemented your suggestions to the page. :)
